version: 2.2.3-{build}
image: Ubuntu
stack: node 12
install:
  - yarn install
build_script:
  # CI=true by default, but then warnings are errors and the build fails due to Cesium
  - export CI=false
  - yarn build
  - docker build .
#test_script:
#  - yarn test
